### ISSUE TITLE
Modifications to the Docker image entrypoint cause long image rebuilds

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-forum#13]
When we make small changes to the docker-entrypoint.sh script (as we did in this PR #10), the Docker image needs to be rebuilt almost from scratch. This because the following statement:

    COPY ./bin /app/bin

is located before the rest of the Dockerfile instructions (including `git clone ...` etc.).

I suggest either to:

1. Move the `COPY` statement closer to the `ENTRYPOINT` statement.
2. Switch to a layer-based build.

**Comment by Marsh-sudo** [comment]
If not solved kindly i would like to help out....thanks :)

**Comment by regisb** [comment]
You're more than welcome @Marsh-sudo, thanks for offering! Please open a pull request :)

**Comment by regisb** [comment]
Hey @Marsh-sudo do you still have time to work on this issue? No pressure, it's perfectly OK if you don't have time to work on it, but we just need to know.

**Comment by Marsh-sudo** [comment]
Yeah am still working on it....will let you know how things are going on👍🏾

**Comment by regisb** [comment]
@Marsh-sudo are you still working on this? If you don't have time it's OK, we can assign the issue to someone else.

**Comment by Marsh-sudo** [comment]
Unfortunately, i have been busy not being able to complete the issue
So just assign someone else and sorry for the inconvenience🙏🏽
