### ISSUE TITLE
Building the forum image fails on arm64

### ISSUE THREAD

**Issue by ghassanmas** [overhangio/tutor-forum#23]
Building the image fails on Arm based arch/(e.g Apple silicon), due to gem lock file not supporting the platform/arch. 
Docker build error: 
```
 => ERROR [stage-0 10/12] RUN bundle install                                                                                                                                 0.3s
------                                                                                                                                                                            
 > [stage-0 10/12] RUN bundle install:                                                                                                                                            
#14 0.280 Your bundle only supports platforms ["x86_64-linux"] but your local platform is                                                                                         
#14 0.280 aarch64-linux. Add the current platform to the lockfile with `bundle lock
#14 0.280 --add-platform aarch64-linux` and try again.
------
executor failed running [/bin/sh -c bundle install]: exit code: 16

``` 
To reproduce, just build the image `tutor images build forum` on a device which  is not Arch x86.  
The suggested fix above does fix it, however it's better to resolve the issue upstream @ https://github.com/openedx/cs_comments_service.

**Comment by regisb** [comment]
Please remember to remove the `IMAGES_BUILD_PLATFORM` variable from .gitlab-ci.yml when this is fixed.

**Comment by ghassanmas** [comment]
@regisb appoligies I forgot to remove  `IMAGES_BUILD_PLATFORM` from `gitlab-ci.yml`, also I found another outdate properties `OPENEDX_RELEASE` which still pointing `lilac`. 

Lastly, regarding the open PR #20, which seems outdate, should I close it, and instead create new entries for v16

**Comment by regisb** [comment]
Yes, you can close #20.

**Comment by regisb** [comment]
Why close this issue? arm64 is still not supported, unless I'm mistaken.

**Comment by regisb** [comment]
Weird... A commit in a separate repo caused this issue to be closed...

**Comment by ghassanmas** [comment]
Aha that bceause I upgraded my fork, and in the last commit I linked it to this issue... Do we need to remove platform form the gitlab ci file in order to close this?

**Comment by regisb** [comment]
Can we now build the image on arm64? If yes then we should remove that line, yes.

**Comment by regisb** [comment]
@ghassanmas can we now build the forum image on arm64?
