### ISSUE TITLE
Multi-tenant Elasticsearch

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor-forum#30]
I was playing with the [Harmony](https://github.com/openedx/openedx-k8s-harmony) project and they mentioned that it's now achievable since https://github.com/openedx/edx-search/pull/130 and https://github.com/openedx/cs_comments_service/pull/404, but I didn't find any configurations related to a `Prefix` for elastic indices. Is this feature implemented or only cs_comment support it and should we modify the plugin? 
I've got the same question for tutor-discovery and any other plugins which are using Elastic Search.

**Comment by regisb** [comment]
If I understand correctly, you would like to define ElasticSearch index name prefixes to facilitate multi-tenancy. (running multiple Open edX platforms on the same ElasticSearch cluster) Did I get this right?

The `ELASTICSEARCH_INDEX_PREFIX` is not a Tutor setting. It is mentioned in https://github.com/openedx/cs_comments_service/pull/404 but only exists in Keith's fork of the forum plugin (see https://github.com/open-craft/tutor-forum/commit/5b57ce3a1664ac8c22e32c47ada4ece72a7f8a37). 

You will have to make use of these settings in your own plugin.

**Comment by CodeWithEmad** [comment]
> Did I get this right?

Exactly!

> The `ELASTICSEARCH_INDEX_PREFIX` is not a Tutor setting.

Can we include multitenant Elastic support in `tutor-forum` plugin later? I could submit a pull request for forum and discovery plugins when I resolve the issue.

**Comment by regisb** [comment]
I don't think we would like to include an Elasticsearch prefix in Tutor core, no.
