### ISSUE TITLE
tutor-forum codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-forum#31]
- [ ] Ensure tutor-forum is compatible with Python 3.12

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by DawoudSheraz** [comment]
@ghassanmas FYI. Please let me know if you need any assistance or information. Thanks

**Comment by kdmccormick** [comment]
@DawoudSheraz you can remove this part:

> Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly.

since this the forums run on Ruby instead of Python.
