### ISSUE TITLE
Failed to connect to MongoDB replicaset

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor-forum#39]
Hi. I have a MongoDB hosted in my cluster, with 3 replicasets. With the tutor, I can use the FQDN as the MONGODB_HOST, but in tutor-forum, It gets stuck in the `docker-entrypoint.sh`, where it tries to wait for the service to be ready. 

```log
2024/07/08 12:16:49 Waiting for tcp://mongodb://mongodb-nightly-0.mongodb-nightly-headless.mongodb-nightly.svc.cluster.local,mongodb-nightly-1.mongodb-nightly-headless.mongodb-nightly.svc.cluster.local,mongodb-nightly-2.mongodb-nightly-headless.mongodb-nightly.svc.cluster.local:27017: dial tcp: lookup mongodb on 10.43.0.10:53: no such host.
```
I know that having a host with `mongodb+srv://` can do the trick, but in my case (and many people), we don't want to expose our service. I know PyMongo can handle these kinda hosts, but does the cs_comment service support too?

**Comment by ghassanmas** [comment]
@CodeWithEmad can you to set port on each host for  `MONGODB_HOST`, I see that the port is set only for the last host.

**Comment by CodeWithEmad** [comment]
@ghassanmas That's because the `docker-entrypoint.sh` added the port, and it doesn't understand the host is not a single address.

https://github.com/overhangio/tutor-forum/blob/829adf25cf1e0c434503eff49fd62480df0e5f7b/tutorforum/templates/forum/build/forum/bin/docker-entrypoint.sh#L12-L15

```yaml
MONGODB_HOST: 'mongodb-nightly-0.mongodb-nightly-headless.mongodb-nightly.svc.cluster.local,mongodb-nightly-1.mongodb-nightly-headless.mongodb-nightly.svc.cluster.local,mongodb-nightly-2.mongodb-nightly-headless.mongodb-nightly.svc.cluster.local'

MONGODB_PORT: 27017
```

**Comment by ghassanmas** [comment]
Aha correct, it only checks if it includes `srv` so that it treats it as a replicaset type of url.
it doesn't wait at all if it has `srv`, I wonder even if `dockerize -wait` would support that type of URL so that we might skip waiting like `srv` case

**Comment by CodeWithEmad** [comment]
I'll try to come up with a fix for this

**Comment by ghassanmas** [comment]
@CodeWithEmad could try to see if #40 would resolve it.

**Comment by CodeWithEmad** [comment]
Thanks @ghassanmas. I'm a bit busy thees week, but I'll make sure to test it with my cluster ASAP.

**Comment by ghassanmas** [comment]
@CodeWithEmad have you had to test yet?

**Comment by CodeWithEmad** [comment]
Hey @ghassanmas. Sorry for the late response and thanks for the PR. I'm afraid not. I'll try to push some work forward and make this happen.
