### ISSUE TITLE
SEARCH_SERVER is not being set as expected when Extermal ES 

### ISSUE THREAD

**Issue by Henrrypg** [overhangio/tutor-forum#50]
# Description

Aparently with [this change](https://github.com/overhangio/tutor-forum/pull/40/files#diff-3a39d7c4e540ad6bf64e887516aaa76359ea211d5438741db56491b557d4801aL53) the [base env](https://github.com/overhangio/tutor-forum/blob/9b09fdaf3a9714148cf4c240c3c7dd84e539810b/tutorforum/plugin.py#L31) should be changed too. Otherwise the ELASTICSEARCH_HOST is being sent but in the wrong variable:

`Faraday::ConnectionFailed: Failed to open TCP connection to elasticsearch:9200 (getaddrinfo: Name or service not known) (Faraday::ConnectionFailed)`

**Comment by Henrrypg** [comment]
@ghassanmas can you look at this?

**Comment by ghassanmas** [comment]
Thank you for the catch! 
 I created #51  to reoslve, by the way, were you installing from the `master` branch?

**Comment by Henrrypg** [comment]
Hi @ghassanmas, i was installing from `sumac` for testing purposes of the new release.

**Comment by DawoudSheraz** [comment]
With sumac release, this is no longer needed because tutor-forum now uses Meilisearch from tutor core instead of ElasticSearch.
