### ISSUE TITLE
API_KEY hardcoded

### ISSUE THREAD

**Issue by dkaliberda** [overhangio/tutor-forum#55]
API_KEY should be able to be changed if necessary.

**Comment by regisb** [comment]
Why?

**Comment by dkaliberda** [comment]
For example, for security reasons.

**Comment by regisb** [comment]
https://docs.tutor.edly.io/troubleshooting.html

> If despite all your efforts, you can’t solve the problem by yourself, you should discuss it in the [Open edX community forum](https://discuss.openedx.org/). Please give as many details about your problem as possible! As a rule of thumb, **people will not dedicate more time to solving your problem than you took to write your question**.

**Comment by dkaliberda** [comment]
I'm sorry, I missed that point.

**Comment by regisb** [comment]
Feel free to re-open this issue if you think you can add more details and background information.
